name = "Craigpeters.me Theme"
license = "GNU"
licenselink = "https://github.com/craigmpeters/craigpetersme-theme/LICENSE"
description = "A theme for craigpeters.me - available to be used by anyone"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.84.0"

[author]
  name = "Craig Peters"
  homepage = "https://github.com/craigmpeters/craigpetersme-theme"
